[project]
name = "calmora"
version = "0.1.0"
description = "Calmora - Mental Health Management Platform"
requires-python = ">=3.10"

dependencies = [
    "Flask",
    "Flask-SQLAlchemy",
    "Flask-Login",
    "Flask-WTF",
    "Flask-Migrate",
    "WTForms",
    "email-validator",
    "python-dotenv",
    "openpyxl",
    "reportlab",
    "Werkzeug",
    "psycopg[binary]"
]

[tool.vercel]
entrypoint = "run:app"